### ISSUE TITLE
Xubuntu 24.04, Qt 6.4.2, mpc-qt 26.07: Failed to build.

### ISSUE THREAD

**Issue by Skif-off** [mpc-qt/mpc-qt#1003]
```
mpc-qt-26.07/src/platform/windowmanager.cpp:164:9: error: 'QGuiApplication' has not been declared
  164 |     if (QGuiApplication::platformName() != "wayland")
      |         ^~~~~~~~~~~~~~~

mpc-qt-26.07/src/settingswindow.cpp: In member function 'void SettingsWindow::sendSignals()':
mpc-qt-26.07/src/settingswindow.cpp:752:62: error: 'class QStyleHints' has no member named 'colorScheme'
  752 |     else if (useDarkColors || QGuiApplication::styleHints()->colorScheme() == Qt::ColorScheme::Dark)
      |                                                              ^~~~~~~~~~~

mpc-qt-26.07/src/settingswindow.cpp:752:83: error: 'Qt::ColorScheme' has not been declared
  752 |     else if (useDarkColors || QGuiApplication::styleHints()->colorScheme() == Qt::ColorScheme::Dark)
      |                                                                                   ^~~~~~~~~~~
```
In the first case, it is enough to add `#include <QGuiApplication>`, but I don't know about the others.

**Comment by tbertels** [comment]
26.07 will still fail to build on Qt < 6.5 since it's already released, but you can build the master branch.

**Comment by Skif-off** [comment]
Thanks!
